import { configureStore } from '@reduxjs/toolkit';

import { apiSlice } from '../features/activity/activitySlice';

export const store = configureStore({
	reducer: {
		// Add autogenerated reducer
		[apiSlice.reducerPath]: apiSlice.reducer,
	},
	middleware: (getDefaultMiddleware) =>
		getDefaultMiddleware().concat(apiSlice.middleware),
});

export type AppDispatch = typeof store.dispatch;
export type RootState = ReturnType<typeof store.getState>;
